<?php

namespace ContainerO58SoGD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSa5ZfPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LSa5ZfP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LSa5ZfP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\DeckRepository', 'getDeckRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\DeckRepository',
        ]);
    }
}
