<?php

namespace ContainerO58SoGD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckApiControllergetFlashcardsByDeckService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rrRFccK.App\Controller\Api\DeckApiController::getFlashcardsByDeck()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rrRFccK.App\\Controller\\Api\\DeckApiController::getFlashcardsByDeck()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deckRepo' => ['privates', 'App\\Repository\\DeckRepository', 'getDeckRepositoryService', true],
        ], [
            'deckRepo' => 'App\\Repository\\DeckRepository',
        ]))->withContext('App\\Controller\\Api\\DeckApiController::getFlashcardsByDeck()', $container);
    }
}
