<?php

namespace ContainerO58SoGD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rLt2rxW.App\Entity\Flashcard' shared service.
     *
     * @return \App\Entity\Flashcard
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rLt2rxW": it needs an instance of "App\\Entity\\Flashcard" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
