<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KXs0lgYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.KXs0lgY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\TagRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.KXs0lgY'])) {
            return $container->privates['.service_locator.KXs0lgY'];
        }

        return $container->privates['.service_locator.KXs0lgY'] = $instance;
    }
}
