<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClassementApiControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\ClassementApiController' shared autowired service.
     *
     * @return \App\Controller\Api\ClassementApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\ClassementApiController'] = $instance = new \App\Controller\Api\ClassementApiController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\ClassementApiController', $container));

        return $instance;
    }
}
