<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DeckRepository' shared autowired service.
     *
     * @return \App\Repository\DeckRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DeckRepository'] = new \App\Repository\DeckRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
