<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckApiControllerdeleteDeckService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xi9MmDs.App\Controller\Api\DeckApiController::deleteDeck()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\DeckRepository', 'getDeckRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\DeckRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Api\\DeckApiController::deleteDeck()', $container);

        if (isset($container->privates['.service_locator.xi9MmDs.App\\Controller\\Api\\DeckApiController::deleteDeck()'])) {
            return $container->privates['.service_locator.xi9MmDs.App\\Controller\\Api\\DeckApiController::deleteDeck()'];
        }

        return $container->privates['.service_locator.xi9MmDs.App\\Controller\\Api\\DeckApiController::deleteDeck()'] = $instance;
    }
}
