<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEaMoneyTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Form\Type\EaMoneyType' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Form\Type\EaMoneyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\EaMoneyType'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\EaMoneyType();
    }
}
