<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\FlashcardCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\FlashcardCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \App\Controller\Admin\FlashcardCrudController();

        if (isset($container->services['App\\Controller\\Admin\\FlashcardCrudController'])) {
            return $container->services['App\\Controller\\Admin\\FlashcardCrudController'];
        }

        $container->services['App\\Controller\\Admin\\FlashcardCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.WOU_dzL'] ?? $container->load('get_ServiceLocator_WOUDzLService'))->withContext('App\\Controller\\Admin\\FlashcardCrudController', $container));

        return $instance;
    }
}
