<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeGuesser_ValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.type_guesser.validator' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Validator\ValidatorTypeGuesser
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['validator'] ?? self::getValidatorService($container));

        if (isset($container->privates['form.type_guesser.validator'])) {
            return $container->privates['form.type_guesser.validator'];
        }

        $instance = new \Symfony\Component\Form\Extension\Validator\ValidatorTypeGuesser($a);

        if (isset($container->privates['form.type_guesser.validator'])) {
            return $container->privates['form.type_guesser.validator'];
        }

        return $container->privates['form.type_guesser.validator'] = $instance;
    }
}
