<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MigrateController' shared autowired service.
     *
     * @return \App\Controller\MigrateController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MigrateController'] = $instance = new \App\Controller\MigrateController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\MigrateController', $container));

        return $instance;
    }
}
