<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevisionLogControllerlogRevisionService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.z0A7H.F.App\Controller\Api\RevisionLogController::logRevision()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.z0A7H.F'] ?? $container->load('get_ServiceLocator_Z0A7H_FService'));

        if (isset($container->privates['.service_locator.z0A7H.F.App\\Controller\\Api\\RevisionLogController::logRevision()'])) {
            return $container->privates['.service_locator.z0A7H.F.App\\Controller\\Api\\RevisionLogController::logRevision()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\RevisionLogController::logRevision()', $container);

        if (isset($container->privates['.service_locator.z0A7H.F.App\\Controller\\Api\\RevisionLogController::logRevision()'])) {
            return $container->privates['.service_locator.z0A7H.F.App\\Controller\\Api\\RevisionLogController::logRevision()'];
        }

        return $container->privates['.service_locator.z0A7H.F.App\\Controller\\Api\\RevisionLogController::logRevision()'] = $instance;
    }
}
