<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevisionLogControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\RevisionLogController' shared autowired service.
     *
     * @return \App\Controller\Api\RevisionLogController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\RevisionLogController'] = $instance = new \App\Controller\Api\RevisionLogController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\RevisionLogController', $container));

        return $instance;
    }
}
