<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagApiControllershowService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.vHgnEho.App\Controller\Api\TagApiController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vHgnEho.App\\Controller\\Api\\TagApiController::show()'] = ($container->privates['.service_locator.vHgnEho'] ?? $container->load('get_ServiceLocator_VHgnEhoService'))->withContext('App\\Controller\\Api\\TagApiController::show()', $container);
    }
}
