<?php

namespace ContainerGr1ILcP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\UserCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\UserCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \App\Controller\Admin\UserCrudController();

        if (isset($container->services['App\\Controller\\Admin\\UserCrudController'])) {
            return $container->services['App\\Controller\\Admin\\UserCrudController'];
        }

        $container->services['App\\Controller\\Admin\\UserCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.WOU_dzL'] ?? $container->load('get_ServiceLocator_WOUDzLService'))->withContext('App\\Controller\\Admin\\UserCrudController', $container));

        return $instance;
    }
}
