<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511235005 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE deck (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, difficulte INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FAC3637A76ED395 ON deck (user_id)');
        $this->addSql('CREATE TABLE deck_tag (deck_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (deck_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_E72958A7111948DC ON deck_tag (deck_id)');
        $this->addSql('CREATE INDEX IDX_E72958A7BAD26311 ON deck_tag (tag_id)');
        $this->addSql('CREATE TABLE flashcard (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deck_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70511A09111948DC ON flashcard (deck_id)');
        $this->addSql('CREATE TABLE revision_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, flashcards_count INT NOT NULL, duration_seconds INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, deck_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99F1649BA76ED395 ON revision_log (user_id)');
        $this->addSql('CREATE INDEX IDX_99F1649B111948DC ON revision_log (deck_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE public."user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, password VARCHAR(255) NOT NULL, image_name VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE deck ADD CONSTRAINT FK_4FAC3637A76ED395 FOREIGN KEY (user_id) REFERENCES public."user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deck_tag ADD CONSTRAINT FK_E72958A7111948DC FOREIGN KEY (deck_id) REFERENCES deck (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE deck_tag ADD CONSTRAINT FK_E72958A7BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE flashcard ADD CONSTRAINT FK_70511A09111948DC FOREIGN KEY (deck_id) REFERENCES deck (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE revision_log ADD CONSTRAINT FK_99F1649BA76ED395 FOREIGN KEY (user_id) REFERENCES public."user" (id)');
        $this->addSql('ALTER TABLE revision_log ADD CONSTRAINT FK_99F1649B111948DC FOREIGN KEY (deck_id) REFERENCES deck (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deck DROP CONSTRAINT FK_4FAC3637A76ED395');
        $this->addSql('ALTER TABLE deck_tag DROP CONSTRAINT FK_E72958A7111948DC');
        $this->addSql('ALTER TABLE deck_tag DROP CONSTRAINT FK_E72958A7BAD26311');
        $this->addSql('ALTER TABLE flashcard DROP CONSTRAINT FK_70511A09111948DC');
        $this->addSql('ALTER TABLE revision_log DROP CONSTRAINT FK_99F1649BA76ED395');
        $this->addSql('ALTER TABLE revision_log DROP CONSTRAINT FK_99F1649B111948DC');
        $this->addSql('DROP TABLE deck');
        $this->addSql('DROP TABLE deck_tag');
        $this->addSql('DROP TABLE flashcard');
        $this->addSql('DROP TABLE revision_log');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE public."user"');
    }
}
