<?php

namespace ContainerUZyAsNP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MHMFXwg.App\Controller\Api\FlashcardApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.MHMFXwg'] ?? $container->load('get_ServiceLocator_MHMFXwgService'));

        if (isset($container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::update()'])) {
            return $container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::update()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\FlashcardApiController::update()', $container);

        if (isset($container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::update()'])) {
            return $container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::update()'];
        }

        return $container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::update()'] = $instance;
    }
}
