<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGr1ILcP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGr1ILcP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGr1ILcP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGr1ILcP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerGr1ILcP\App_KernelProdContainer([
    'container.build_hash' => 'Gr1ILcP',
    'container.build_id' => '4fa86b3e',
    'container.build_time' => 1778542064,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGr1ILcP');
