<?php

namespace ContainerQjAXYXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckApiControllermyDecksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LSa5ZfP.App\Controller\Api\DeckApiController::myDecks()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LSa5ZfP.App\\Controller\\Api\\DeckApiController::myDecks()'] = ($container->privates['.service_locator.LSa5ZfP'] ?? $container->load('get_ServiceLocator_LSa5ZfPService'))->withContext('App\\Controller\\Api\\DeckApiController::myDecks()', $container);
    }
}
