<?php

namespace ContainerQjAXYXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardApiControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g5gvHJi.App\Controller\Api\FlashcardApiController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'deckRepo' => ['privates', 'App\\Repository\\DeckRepository', 'getDeckRepositoryService', true],
        ], [
            'em' => '?',
            'deckRepo' => 'App\\Repository\\DeckRepository',
        ]))->withContext('App\\Controller\\Api\\FlashcardApiController::create()', $container);

        if (isset($container->privates['.service_locator.g5gvHJi.App\\Controller\\Api\\FlashcardApiController::create()'])) {
            return $container->privates['.service_locator.g5gvHJi.App\\Controller\\Api\\FlashcardApiController::create()'];
        }

        return $container->privates['.service_locator.g5gvHJi.App\\Controller\\Api\\FlashcardApiController::create()'] = $instance;
    }
}
