<?php

namespace ContainerLJlkr0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VHgnEhoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vHgnEho' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vHgnEho'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tag' => ['privates', '.errored..service_locator.vHgnEho.App\\Entity\\Tag', NULL, 'Cannot autowire service ".service_locator.vHgnEho": it needs an instance of "App\\Entity\\Tag" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'tag' => 'App\\Entity\\Tag',
        ]);
    }
}
