<?php

namespace ContainerLJlkr0I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Command/DebugFirewallCommand.php';

        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.xI8iHba'] ?? self::get_ServiceLocator_XI8iHbaService($container)), ($container->privates['.service_locator.sTR9VIc'] ?? $container->load('get_ServiceLocator_STR9VIcService')), ['login' => [($container->privates['debug.security.authenticator.json_login.login'] ?? $container->load('getDebug_Security_Authenticator_JsonLogin_LoginService'))], 'api' => [($container->privates['debug.security.authenticator.jwt.api'] ?? $container->load('getDebug_Security_Authenticator_Jwt_ApiService'))], 'main' => [($container->privates['debug.security.authenticator.form_login.main'] ?? $container->load('getDebug_Security_Authenticator_FormLogin_MainService'))]], false);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
