<?php

namespace ContainerXaB5dCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardCrudControllerupdateEntityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3BoFVFw.App\Controller\Admin\FlashcardCrudController::updateEntity()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.3BoFVFw'] ?? $container->load('get_ServiceLocator_3BoFVFwService'));

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\Admin\\FlashcardCrudController::updateEntity()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\Admin\\FlashcardCrudController::updateEntity()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\FlashcardCrudController::updateEntity()', $container);

        if (isset($container->privates['.service_locator.3BoFVFw.App\\Controller\\Admin\\FlashcardCrudController::updateEntity()'])) {
            return $container->privates['.service_locator.3BoFVFw.App\\Controller\\Admin\\FlashcardCrudController::updateEntity()'];
        }

        return $container->privates['.service_locator.3BoFVFw.App\\Controller\\Admin\\FlashcardCrudController::updateEntity()'] = $instance;
    }
}
