<?php

namespace ContainerXaB5dCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateControllerdebugDbInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rbVYtVl.App\Controller\MigrateController::debugDbInfo()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rbVYtVl.App\\Controller\\MigrateController::debugDbInfo()'] = ($container->privates['.service_locator.rbVYtVl'] ?? $container->load('get_ServiceLocator_RbVYtVlService'))->withContext('App\\Controller\\MigrateController::debugDbInfo()', $container);
    }
}
