<?php

namespace ContainerXaB5dCw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevisionLogCrudControllerconfigureActionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MygkM6_.App\Controller\Admin\RevisionLogCrudController::configureActions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MygkM6_.App\\Controller\\Admin\\RevisionLogCrudController::configureActions()'] = ($container->privates['.service_locator.MygkM6_'] ?? $container->load('get_ServiceLocator_MygkM6Service'))->withContext('App\\Controller\\Admin\\RevisionLogCrudController::configureActions()', $container);
    }
}
