<?php

namespace ContainerX4dFzC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckApiControllercreateDeckService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uac5_wE.App\Controller\Api\DeckApiController::createDeck()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tagRepo' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'em' => '?',
            'tagRepo' => 'App\\Repository\\TagRepository',
        ]))->withContext('App\\Controller\\Api\\DeckApiController::createDeck()', $container);

        if (isset($container->privates['.service_locator.Uac5_wE.App\\Controller\\Api\\DeckApiController::createDeck()'])) {
            return $container->privates['.service_locator.Uac5_wE.App\\Controller\\Api\\DeckApiController::createDeck()'];
        }

        return $container->privates['.service_locator.Uac5_wE.App\\Controller\\Api\\DeckApiController::createDeck()'] = $instance;
    }
}
