<?php

namespace ContainerX4dFzC4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagApiControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.crqc3Ue.App\Controller\Api\TagApiController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.crqc3Ue.App\\Controller\\Api\\TagApiController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\TagRepository',
        ]))->withContext('App\\Controller\\Api\\TagApiController::index()', $container);
    }
}
