<?php

namespace ContainerXZ4iDPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\FlashcardApiController' shared autowired service.
     *
     * @return \App\Controller\Api\FlashcardApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/FlashcardApiController.php';

        $container->services['App\\Controller\\Api\\FlashcardApiController'] = $instance = new \App\Controller\Api\FlashcardApiController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\FlashcardApiController', $container));

        return $instance;
    }
}
