<?php

namespace ContainerXZ4iDPS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KXs0lgY.App\Controller\Api\TagApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.KXs0lgY'] ?? $container->load('get_ServiceLocator_KXs0lgYService'));

        if (isset($container->privates['.service_locator.KXs0lgY.App\\Controller\\Api\\TagApiController::update()'])) {
            return $container->privates['.service_locator.KXs0lgY.App\\Controller\\Api\\TagApiController::update()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\TagApiController::update()', $container);

        if (isset($container->privates['.service_locator.KXs0lgY.App\\Controller\\Api\\TagApiController::update()'])) {
            return $container->privates['.service_locator.KXs0lgY.App\\Controller\\Api\\TagApiController::update()'];
        }

        return $container->privates['.service_locator.KXs0lgY.App\\Controller\\Api\\TagApiController::update()'] = $instance;
    }
}
