<?php

namespace ContainerZ5iLxZ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeckApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ods9VWJ.App\Controller\Api\DeckApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\DeckRepository', 'getDeckRepositoryService', true],
            'tagRepo' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\DeckRepository',
            'tagRepo' => 'App\\Repository\\TagRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\Api\\DeckApiController::update()', $container);

        if (isset($container->privates['.service_locator.ods9VWJ.App\\Controller\\Api\\DeckApiController::update()'])) {
            return $container->privates['.service_locator.ods9VWJ.App\\Controller\\Api\\DeckApiController::update()'];
        }

        return $container->privates['.service_locator.ods9VWJ.App\\Controller\\Api\\DeckApiController::update()'] = $instance;
    }
}
