<?php

namespace ContainerRGHBy4D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MHMFXwgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MHMFXwg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\FlashcardRepository', 'getFlashcardRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\FlashcardRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.MHMFXwg'])) {
            return $container->privates['.service_locator.MHMFXwg'];
        }

        return $container->privates['.service_locator.MHMFXwg'] = $instance;
    }
}
