<?php

namespace ContainerRGHBy4D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MHMFXwg.App\Controller\Api\FlashcardApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.MHMFXwg'] ?? $container->load('get_ServiceLocator_MHMFXwgService'));

        if (isset($container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::delete()'])) {
            return $container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\FlashcardApiController::delete()', $container);

        if (isset($container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::delete()'])) {
            return $container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::delete()'];
        }

        return $container->privates['.service_locator.MHMFXwg.App\\Controller\\Api\\FlashcardApiController::delete()'] = $instance;
    }
}
