<?php

namespace ContainerRGHBy4D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlashcardApiControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rLt2rxW.App\Controller\Api\FlashcardApiController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rLt2rxW.App\\Controller\\Api\\FlashcardApiController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'card' => ['privates', '.errored..service_locator.rLt2rxW.App\\Entity\\Flashcard', NULL, 'Cannot autowire service ".service_locator.rLt2rxW": it needs an instance of "App\\Entity\\Flashcard" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'card' => 'App\\Entity\\Flashcard',
        ]))->withContext('App\\Controller\\Api\\FlashcardApiController::show()', $container);
    }
}
