<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO58SoGD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO58SoGD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO58SoGD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO58SoGD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO58SoGD\App_KernelDevDebugContainer([
    'container.build_hash' => 'O58SoGD',
    'container.build_id' => 'ec0f282d',
    'container.build_time' => 1778525067,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO58SoGD');
