<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4dFzC4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4dFzC4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4dFzC4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4dFzC4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4dFzC4\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4dFzC4',
    'container.build_id' => 'c50b67c4',
    'container.build_time' => 1778530651,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4dFzC4');
